services:
  - type: web
    name: express-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: node --max-old-space-size=4096 dist/index.js

    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
